*** Variables ***
${TITLE_TASK}     id=com.avjindersinghsekhon.minimaltodo:id/toDoListItemTextview
${ICON_ADD}       id=com.avjindersinghsekhon.minimaltodo:id/addToDoItemFAB
${ICON_KEBAB}     xpath=//android.widget.ImageView[@content-desc="More options"]
${TAB_SETTING}    xpath=//android.widget.TextView[@resource-id="com.avjindersinghsekhon.minimaltodo:id/title" and @text="Settings"]
${TAB_ABOUT}      xpath=//android.widget.TextView[@resource-id="com.avjindersinghsekhon.minimaltodo:id/title" and @text="About"]